package com.person.website.pojo;

import java.io.Serializable;

public class District implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.id
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.pid
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.district_name
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.type
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.hierarchy
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private Integer hierarchy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.district_sqe
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private String districtSqe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_district
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.id
     *
     * @return the value of t_district.id
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.id
     *
     * @param id the value for t_district.id
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.pid
     *
     * @return the value of t_district.pid
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.pid
     *
     * @param pid the value for t_district.pid
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.district_name
     *
     * @return the value of t_district.district_name
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.district_name
     *
     * @param districtName the value for t_district.district_name
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.type
     *
     * @return the value of t_district.type
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.type
     *
     * @param type the value for t_district.type
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.hierarchy
     *
     * @return the value of t_district.hierarchy
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public Integer getHierarchy() {
        return hierarchy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.hierarchy
     *
     * @param hierarchy the value for t_district.hierarchy
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public void setHierarchy(Integer hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.district_sqe
     *
     * @return the value of t_district.district_sqe
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public String getDistrictSqe() {
        return districtSqe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.district_sqe
     *
     * @param districtSqe the value for t_district.district_sqe
     *
     * @mbggenerated Tue Oct 12 11:05:38 CST 2021
     */
    public void setDistrictSqe(String districtSqe) {
        this.districtSqe = districtSqe == null ? null : districtSqe.trim();
    }
}