package com.person.website.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_tradeno
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private String payTradeno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_amount
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private BigDecimal payAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_tradeno
     *
     * @return the value of t_order.pay_tradeno
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public String getPayTradeno() {
        return payTradeno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_tradeno
     *
     * @param payTradeno the value for t_order.pay_tradeno
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public void setPayTradeno(String payTradeno) {
        this.payTradeno = payTradeno == null ? null : payTradeno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_id
     *
     * @return the value of t_order.pay_id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_id
     *
     * @param payId the value for t_order.pay_id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_amount
     *
     * @return the value of t_order.pay_amount
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_amount
     *
     * @param payAmount the value for t_order.pay_amount
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbggenerated Sun Dec 19 17:34:26 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}