package com.person.website.pojo;

import java.io.Serializable;
import java.util.Date;

public class Picture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.pic_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.pic_name
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.pic_url
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.pic_classification
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Byte picClassification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.type
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.pic_state
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Byte picState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.user_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_picture.upload_time
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.id
     *
     * @return the value of t_picture.id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.id
     *
     * @param id the value for t_picture.id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.pic_id
     *
     * @return the value of t_picture.pic_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.pic_id
     *
     * @param picId the value for t_picture.pic_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setPicId(String picId) {
        this.picId = picId == null ? null : picId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.pic_name
     *
     * @return the value of t_picture.pic_name
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.pic_name
     *
     * @param picName the value for t_picture.pic_name
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.pic_url
     *
     * @return the value of t_picture.pic_url
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.pic_url
     *
     * @param picUrl the value for t_picture.pic_url
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.pic_classification
     *
     * @return the value of t_picture.pic_classification
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Byte getPicClassification() {
        return picClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.pic_classification
     *
     * @param picClassification the value for t_picture.pic_classification
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setPicClassification(Byte picClassification) {
        this.picClassification = picClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.type
     *
     * @return the value of t_picture.type
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.type
     *
     * @param type the value for t_picture.type
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.pic_state
     *
     * @return the value of t_picture.pic_state
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Byte getPicState() {
        return picState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.pic_state
     *
     * @param picState the value for t_picture.pic_state
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setPicState(Byte picState) {
        this.picState = picState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.user_id
     *
     * @return the value of t_picture.user_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.user_id
     *
     * @param userId the value for t_picture.user_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_picture.upload_time
     *
     * @return the value of t_picture.upload_time
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_picture.upload_time
     *
     * @param uploadTime the value for t_picture.upload_time
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}