package com.person.website.pojo;

import java.io.Serializable;

public class Resume implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.id
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.job_posts
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String jobPosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.sex
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.age
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.computer_skill
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String computerSkill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.tel
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.email
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.home_page
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String homePage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.git_hub
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String gitHub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.gitee
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String gitee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.backend_framework
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String backendFramework;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.front_end_framework
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String frontEndFramework;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.database_related
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String databaseRelated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.development_tools
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String developmentTools;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.version_management
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String versionManagement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.other_skills
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String otherSkills;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.education
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.work_experience
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String workExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.status
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.duty_time
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String dutyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.dream_position
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String dreamPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.dream_city
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String dreamCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.company_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.development_project_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String developmentProjectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.start_date
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.end_date
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.project_intro
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String projectIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.reason_for_leaving
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String reasonForLeaving;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.project_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.project_description
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String projectDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.self_evaluation
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String selfEvaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resume.user_id
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_resume
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.id
     *
     * @return the value of t_resume.id
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.id
     *
     * @param id the value for t_resume.id
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.name
     *
     * @return the value of t_resume.name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.name
     *
     * @param name the value for t_resume.name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.job_posts
     *
     * @return the value of t_resume.job_posts
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getJobPosts() {
        return jobPosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.job_posts
     *
     * @param jobPosts the value for t_resume.job_posts
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setJobPosts(String jobPosts) {
        this.jobPosts = jobPosts == null ? null : jobPosts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.sex
     *
     * @return the value of t_resume.sex
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.sex
     *
     * @param sex the value for t_resume.sex
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.age
     *
     * @return the value of t_resume.age
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.age
     *
     * @param age the value for t_resume.age
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.computer_skill
     *
     * @return the value of t_resume.computer_skill
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getComputerSkill() {
        return computerSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.computer_skill
     *
     * @param computerSkill the value for t_resume.computer_skill
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setComputerSkill(String computerSkill) {
        this.computerSkill = computerSkill == null ? null : computerSkill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.tel
     *
     * @return the value of t_resume.tel
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.tel
     *
     * @param tel the value for t_resume.tel
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.email
     *
     * @return the value of t_resume.email
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.email
     *
     * @param email the value for t_resume.email
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.home_page
     *
     * @return the value of t_resume.home_page
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getHomePage() {
        return homePage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.home_page
     *
     * @param homePage the value for t_resume.home_page
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setHomePage(String homePage) {
        this.homePage = homePage == null ? null : homePage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.git_hub
     *
     * @return the value of t_resume.git_hub
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getGitHub() {
        return gitHub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.git_hub
     *
     * @param gitHub the value for t_resume.git_hub
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setGitHub(String gitHub) {
        this.gitHub = gitHub == null ? null : gitHub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.gitee
     *
     * @return the value of t_resume.gitee
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getGitee() {
        return gitee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.gitee
     *
     * @param gitee the value for t_resume.gitee
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setGitee(String gitee) {
        this.gitee = gitee == null ? null : gitee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.backend_framework
     *
     * @return the value of t_resume.backend_framework
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getBackendFramework() {
        return backendFramework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.backend_framework
     *
     * @param backendFramework the value for t_resume.backend_framework
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setBackendFramework(String backendFramework) {
        this.backendFramework = backendFramework == null ? null : backendFramework.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.front_end_framework
     *
     * @return the value of t_resume.front_end_framework
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getFrontEndFramework() {
        return frontEndFramework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.front_end_framework
     *
     * @param frontEndFramework the value for t_resume.front_end_framework
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setFrontEndFramework(String frontEndFramework) {
        this.frontEndFramework = frontEndFramework == null ? null : frontEndFramework.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.database_related
     *
     * @return the value of t_resume.database_related
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getDatabaseRelated() {
        return databaseRelated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.database_related
     *
     * @param databaseRelated the value for t_resume.database_related
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setDatabaseRelated(String databaseRelated) {
        this.databaseRelated = databaseRelated == null ? null : databaseRelated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.development_tools
     *
     * @return the value of t_resume.development_tools
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getDevelopmentTools() {
        return developmentTools;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.development_tools
     *
     * @param developmentTools the value for t_resume.development_tools
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setDevelopmentTools(String developmentTools) {
        this.developmentTools = developmentTools == null ? null : developmentTools.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.version_management
     *
     * @return the value of t_resume.version_management
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getVersionManagement() {
        return versionManagement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.version_management
     *
     * @param versionManagement the value for t_resume.version_management
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setVersionManagement(String versionManagement) {
        this.versionManagement = versionManagement == null ? null : versionManagement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.other_skills
     *
     * @return the value of t_resume.other_skills
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getOtherSkills() {
        return otherSkills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.other_skills
     *
     * @param otherSkills the value for t_resume.other_skills
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setOtherSkills(String otherSkills) {
        this.otherSkills = otherSkills == null ? null : otherSkills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.education
     *
     * @return the value of t_resume.education
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.education
     *
     * @param education the value for t_resume.education
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.work_experience
     *
     * @return the value of t_resume.work_experience
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getWorkExperience() {
        return workExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.work_experience
     *
     * @param workExperience the value for t_resume.work_experience
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setWorkExperience(String workExperience) {
        this.workExperience = workExperience == null ? null : workExperience.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.status
     *
     * @return the value of t_resume.status
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.status
     *
     * @param status the value for t_resume.status
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.duty_time
     *
     * @return the value of t_resume.duty_time
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getDutyTime() {
        return dutyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.duty_time
     *
     * @param dutyTime the value for t_resume.duty_time
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setDutyTime(String dutyTime) {
        this.dutyTime = dutyTime == null ? null : dutyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.dream_position
     *
     * @return the value of t_resume.dream_position
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getDreamPosition() {
        return dreamPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.dream_position
     *
     * @param dreamPosition the value for t_resume.dream_position
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setDreamPosition(String dreamPosition) {
        this.dreamPosition = dreamPosition == null ? null : dreamPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.dream_city
     *
     * @return the value of t_resume.dream_city
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getDreamCity() {
        return dreamCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.dream_city
     *
     * @param dreamCity the value for t_resume.dream_city
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setDreamCity(String dreamCity) {
        this.dreamCity = dreamCity == null ? null : dreamCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.company_name
     *
     * @return the value of t_resume.company_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.company_name
     *
     * @param companyName the value for t_resume.company_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.development_project_name
     *
     * @return the value of t_resume.development_project_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getDevelopmentProjectName() {
        return developmentProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.development_project_name
     *
     * @param developmentProjectName the value for t_resume.development_project_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setDevelopmentProjectName(String developmentProjectName) {
        this.developmentProjectName = developmentProjectName == null ? null : developmentProjectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.start_date
     *
     * @return the value of t_resume.start_date
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.start_date
     *
     * @param startDate the value for t_resume.start_date
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.end_date
     *
     * @return the value of t_resume.end_date
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.end_date
     *
     * @param endDate the value for t_resume.end_date
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.project_intro
     *
     * @return the value of t_resume.project_intro
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getProjectIntro() {
        return projectIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.project_intro
     *
     * @param projectIntro the value for t_resume.project_intro
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setProjectIntro(String projectIntro) {
        this.projectIntro = projectIntro == null ? null : projectIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.reason_for_leaving
     *
     * @return the value of t_resume.reason_for_leaving
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getReasonForLeaving() {
        return reasonForLeaving;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.reason_for_leaving
     *
     * @param reasonForLeaving the value for t_resume.reason_for_leaving
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setReasonForLeaving(String reasonForLeaving) {
        this.reasonForLeaving = reasonForLeaving == null ? null : reasonForLeaving.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.project_name
     *
     * @return the value of t_resume.project_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.project_name
     *
     * @param projectName the value for t_resume.project_name
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.project_description
     *
     * @return the value of t_resume.project_description
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.project_description
     *
     * @param projectDescription the value for t_resume.project_description
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setProjectDescription(String projectDescription) {
        this.projectDescription = projectDescription == null ? null : projectDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.self_evaluation
     *
     * @return the value of t_resume.self_evaluation
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getSelfEvaluation() {
        return selfEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.self_evaluation
     *
     * @param selfEvaluation the value for t_resume.self_evaluation
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setSelfEvaluation(String selfEvaluation) {
        this.selfEvaluation = selfEvaluation == null ? null : selfEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resume.user_id
     *
     * @return the value of t_resume.user_id
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resume.user_id
     *
     * @param userId the value for t_resume.user_id
     *
     * @mbggenerated Sun Dec 19 13:36:55 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}