package com.person.website.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_avatar
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String userAvatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_sex
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.ip
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.free_space
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private Byte freeSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.space_state
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private Byte spaceState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.account_state
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private Byte accountState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.province
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.city
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.county
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.address
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.left_wish
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String leftWish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.right_whisper
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String rightWhisper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.reg_time
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.up_time
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private Date upTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.carousel
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private String carousel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_avatar
     *
     * @return the value of t_user.user_avatar
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getUserAvatar() {
        return userAvatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_avatar
     *
     * @param userAvatar the value for t_user.user_avatar
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar == null ? null : userAvatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_sex
     *
     * @return the value of t_user.user_sex
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_sex
     *
     * @param userSex the value for t_user.user_sex
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.ip
     *
     * @return the value of t_user.ip
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.ip
     *
     * @param ip the value for t_user.ip
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.free_space
     *
     * @return the value of t_user.free_space
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public Byte getFreeSpace() {
        return freeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.free_space
     *
     * @param freeSpace the value for t_user.free_space
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setFreeSpace(Byte freeSpace) {
        this.freeSpace = freeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.space_state
     *
     * @return the value of t_user.space_state
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public Byte getSpaceState() {
        return spaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.space_state
     *
     * @param spaceState the value for t_user.space_state
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setSpaceState(Byte spaceState) {
        this.spaceState = spaceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.account_state
     *
     * @return the value of t_user.account_state
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public Byte getAccountState() {
        return accountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.account_state
     *
     * @param accountState the value for t_user.account_state
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setAccountState(Byte accountState) {
        this.accountState = accountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.province
     *
     * @return the value of t_user.province
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.province
     *
     * @param province the value for t_user.province
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.city
     *
     * @return the value of t_user.city
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.city
     *
     * @param city the value for t_user.city
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.county
     *
     * @return the value of t_user.county
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.county
     *
     * @param county the value for t_user.county
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.address
     *
     * @return the value of t_user.address
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.address
     *
     * @param address the value for t_user.address
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.left_wish
     *
     * @return the value of t_user.left_wish
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getLeftWish() {
        return leftWish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.left_wish
     *
     * @param leftWish the value for t_user.left_wish
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setLeftWish(String leftWish) {
        this.leftWish = leftWish == null ? null : leftWish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.right_whisper
     *
     * @return the value of t_user.right_whisper
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getRightWhisper() {
        return rightWhisper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.right_whisper
     *
     * @param rightWhisper the value for t_user.right_whisper
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setRightWhisper(String rightWhisper) {
        this.rightWhisper = rightWhisper == null ? null : rightWhisper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.reg_time
     *
     * @return the value of t_user.reg_time
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.reg_time
     *
     * @param regTime the value for t_user.reg_time
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.up_time
     *
     * @return the value of t_user.up_time
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public Date getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.up_time
     *
     * @param upTime the value for t_user.up_time
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setUpTime(Date upTime) {
        this.upTime = upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.carousel
     *
     * @return the value of t_user.carousel
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public String getCarousel() {
        return carousel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.carousel
     *
     * @param carousel the value for t_user.carousel
     *
     * @mbggenerated Thu Oct 28 17:42:58 CST 2021
     */
    public void setCarousel(String carousel) {
        this.carousel = carousel == null ? null : carousel.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", userAvatar='" + userAvatar + '\'' +
                ", userName='" + userName + '\'' +
                ", userSex='" + userSex + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", ip='" + ip + '\'' +
                ", password='" + password + '\'' +
                ", freeSpace=" + freeSpace +
                ", spaceState=" + spaceState +
                ", accountState=" + accountState +
                ", province='" + province + '\'' +
                ", city='" + city + '\'' +
                ", county='" + county + '\'' +
                ", address='" + address + '\'' +
                ", leftWish='" + leftWish + '\'' +
                ", rightWhisper='" + rightWhisper + '\'' +
                ", regTime=" + regTime +
                ", upTime=" + upTime +
                ", carousel='" + carousel + '\'' +
                '}';
    }
}