package com.person.website.pojo;

import java.io.Serializable;
import java.util.Date;

public class Video implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_name
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String videoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_url
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_pic
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String videoPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_classification
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Byte videoClassification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.type
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.video_state
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Byte videoState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.user_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_video.upload_time
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_video
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.id
     *
     * @return the value of t_video.id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.id
     *
     * @param id the value for t_video.id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_id
     *
     * @return the value of t_video.video_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_id
     *
     * @param videoId the value for t_video.video_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_name
     *
     * @return the value of t_video.video_name
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_name
     *
     * @param videoName the value for t_video.video_name
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_url
     *
     * @return the value of t_video.video_url
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_url
     *
     * @param videoUrl the value for t_video.video_url
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_pic
     *
     * @return the value of t_video.video_pic
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getVideoPic() {
        return videoPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_pic
     *
     * @param videoPic the value for t_video.video_pic
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setVideoPic(String videoPic) {
        this.videoPic = videoPic == null ? null : videoPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_classification
     *
     * @return the value of t_video.video_classification
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Byte getVideoClassification() {
        return videoClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_classification
     *
     * @param videoClassification the value for t_video.video_classification
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setVideoClassification(Byte videoClassification) {
        this.videoClassification = videoClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.type
     *
     * @return the value of t_video.type
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.type
     *
     * @param type the value for t_video.type
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.video_state
     *
     * @return the value of t_video.video_state
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Byte getVideoState() {
        return videoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.video_state
     *
     * @param videoState the value for t_video.video_state
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setVideoState(Byte videoState) {
        this.videoState = videoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.user_id
     *
     * @return the value of t_video.user_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.user_id
     *
     * @param userId the value for t_video.user_id
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_video.upload_time
     *
     * @return the value of t_video.upload_time
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_video.upload_time
     *
     * @param uploadTime the value for t_video.upload_time
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }
}