package com.person.website.mapper;

import com.person.website.pojo.Picture;

import java.util.List;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    int insertSelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    Picture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    int updateByPrimaryKeySelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_picture
     *
     * @mbggenerated Sat Dec 04 14:51:37 CST 2021
     */
    int updateByPrimaryKey(Picture record);

    int selectPictureCountByUserId(String userId);

    /**
     * 根据相册id 更新相册信息
     * @param picture 相册图片
     * @return 返回影响的记录数
     */
    int updateByPrimaryKeySelectiveByPictureId(Picture picture);

    /**
     * 查询用户的所有相册
     * @param userId 用户id
     * @return 返回集合
     */
    List<Picture> selectPictureByUserId(String userId);

    /**
     * 查询所有相册数据
     * @return 返回list集合
     */
    List<Picture> selectAll();

    /**
     * 根据相册id查询数据
     * @param pictureId 相册id
     * @return 返回list集合
     */
    List<Picture> selectPictureByPictureId(String pictureId);

    /**
     * 根据相册id删除数据
     * @param pictureId 相册id
     * @return 返回记录数
     */
    int deleteByPictureId(String pictureId);
}